### ISSUE TITLE
Not an issue, but...

### ISSUE THREAD

**Issue by korewatori** [m1chaelbarry/my-bot#1]
This isn't an issue, or related to this repository at all, but I'd like to ask what happened to your MegaClone repository? It was a good project and worked quite well for what I was using it for. I wanted to know whether you had received a request to delete it or whether you just deleted it out of your own will. Thanks!
https://github.com/m1chaelbarry/megaclone
![image](https://user-images.githubusercontent.com/76889884/167516348-a83aa26d-7af1-4369-91c5-7787660d9338.png)

-------------------------------------------------------------------------------------------------------
To nie jest problem, ani nie jest w ogóle związane z tym repozytorium, ale chciałbym zapytać, co się stało z twoim repozytorium MegaClone? To był dobry projekt i działał całkiem nieźle do tego, do czego go używałem. Chciałbym się dowiedzieć, czy otrzymałeś prośbę o jego usunięcie, czy po prostu usunąłeś je z własnej woli. Dzięki!

**Comment by m1chaelbarry** [comment]
I wasn't really happy with it so I made repo private and wanted to remake it but didn't have time for it. I will make it public in a sec
